### ISSUE TITLE
Consider using #![allow(clippy)] at top of generated files

### ISSUE THREAD

**Issue by j-t-d** [capnproto/capnproto-rust#89]
Clippy is giving a lot of warnings in the generated rust files. Using #![allow(clippy)] will disable clippy according to https://github.com/rust-lang-nursery/rust-clippy/issues/702

**Comment by dwrensha** [comment]
How dire are the warnings? Would it be feasible to instead enhance `capnpc-rust` so that it generates clippy-appeasing code?

If not, then `#![allow(clippy)]` sounds good to me.

**Comment by j-t-d** [comment]
They're not too bad:

Lots of these
```
warning: long literal lacking separators
    |
689 |         pub const TYPE_ID: u64 = 0x8bc07f8159567336;
    |                                  ^^^^^^^^^^^^^^^^^^
    |
    = help: consider: 0x8bc0_7f81_5956_7336
    = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.186/index.html#unreadable_literal
```

and these:

```
warning: explicit lifetimes given in parameter types where they could be elided
   |
39 | /     pub fn borrow<'b>(&'b self) -> Reader<'b,> {
40 | |       Reader { .. *self }
41 | |     }
   | |_____^
   |
   = note: #[warn(needless_lifetimes)] on by default
   = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.186/index.html#needless_lifetimes
```

And these:
```
warning: unneeded return statement
    |
280 |           x => return ::std::result::Result::Err(::capnp::NotInSchema(x))
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: remove `return` as shown: `::std::result::Result::Err(::capnp::NotInSchema(x))`
    |
    = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.186/index.html#needless_return
```

**Comment by Deedasmi** [comment]
There are also a few:

* redundant_field_names. There are a few struct initializations that do `reader: reader` which can be shortened to `reader`

* wrong_self_convention because as_reader() should be called into_reader()

* module_inception This one actually probably should be just be marked allowed.

**Comment by Deedasmi** [comment]
Yeah, looks like that was added in 1.17. still, should block the lint with a comment why it's being blocked.

**Comment by ysimonson** [comment]
Most (all?) warnings should be addressed in #112 and #113

**Comment by dwrensha** [comment]
Closing, as #112 and #113 have been merged.

**Comment by mraerino** [comment]
i'm still getting a bunch of warnings, mostly `clippy::redundant-field-names`

is the plan still to fix individual instances of this instead of ignoring lints in the generated files?

**Comment by dwrensha** [comment]
Thanks for the report. Does this fix it? 9405636cc6312aa5e349505195f30c035f17b82c
If not, can you please show the errors that you're seeing?

**Comment by mraerino** [comment]
yup, that seems to have done it. thank you!
are you going to release this soon?

**Comment by dwrensha** [comment]
Pushed 0.13.1 just now: https://crates.io/crates/capnpc
